# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  core_config = debug
endif
ifeq ($(config),release)
  core_config = release
endif

PROJECTS := core

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

core:
ifneq (,$(core_config))
	@echo "==== Building core ($(core_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(core_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   core"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"